Email
MyWishPlatform/mywill_backend pull request #58
Opened 2021-06-22 23:17 UTC by Pechenuca

2021-06-22 23:22 UTC, Pechenuca commented
Пулл реквест курильщика

2021-06-23 09:49 UTC, yulian-khalitov requested changes

2021-06-23 09:49 UTC, yulian-khalitov commented on lastwill/contracts/submodels/common.py
> +                if self.contract.network.id in NETWORK_TYPES['testnet']:
лучше сделать break внутри цикла, если все-таки добрались до мейннет токена и в else после цикла запихнуть отправку обычного сообщения

```
for:
    if token:
      # ....
      break
else:
   # send default message
```

2021-06-29 23:27 UTC, yulian-khalitov approved these changes

2021-06-29 23:28 UTC, merged